import { tokens as t } from "./tokens";

// Mermaid's "base" theme takes its colors from themeVariables
export const mermaidConfig = {
    startOnLoad: false,
    securityLevel: "loose",
    fontFamily: "inherit",
    theme: "base",
    themeVariables: {
        darkMode: true,
        fontFamily: "inherit",
        fontSize: "14px",
        background: t.page,
        primaryColor: t.surface,
        primaryTextColor: t.ink,
        primaryBorderColor: t.lineStrong,
        secondaryColor: t.recess,
        secondaryTextColor: t.inkSoft,
        secondaryBorderColor: t.line,
        tertiaryColor: t.hover,
        tertiaryTextColor: t.inkSoft,
        tertiaryBorderColor: t.lineHover,
        mainBkg: t.surface,
        nodeBorder: t.lineStrong,
        nodeTextColor: t.ink,
        textColor: t.inkSoft,
        lineColor: t.inkFaint,
        titleColor: t.inkLink,
        clusterBkg: t.recess,
        clusterBorder: t.line,
        edgeLabelBackground: t.page,
        noteBkgColor: t.hover,
        noteTextColor: t.inkSoft,
        noteBorderColor: t.lineHover,
        actorBkg: t.surface,
        actorBorder: t.lineStrong,
        actorTextColor: t.ink,
        actorLineColor: t.lineHover,
        signalColor: t.ink2,
        signalTextColor: t.inkSoft,
        labelBoxBkgColor: t.surface,
        labelBoxBorderColor: t.lineStrong,
        labelTextColor: t.ink,
        loopTextColor: t.inkSoft,
        activationBkgColor: t.tile,
        activationBorderColor: t.lineStrong,
        sequenceNumberColor: t.page,
        pie1: t.cat1,
        pie2: t.cat2,
        pie3: t.cat3,
        pie4: t.cat4,
        pie5: t.cat5,
        pieTitleTextColor: t.ink,
        pieSectionTextColor: t.page,
        pieLegendTextColor: t.inkSoft,
        pieStrokeColor: t.page,
        pieOuterStrokeColor: t.line,
    },
} as const;
